title: "米香苑"
description: "以佛法為錨，占卜為光。在最迷茫的時刻，為你照見方向"
taglong: "以佛法為錨，占卜為光<br>在最迷茫的時刻，為你照見方向"
photo: assets/files/avatar.png
baseurl: ""
url: "https://omzen.space"

author:
  name: "子媚"
  email: "omahum110@gmail.com"

profile:
  instagram: https://www.instagram.com/omzen.space
  youtube: https://www.youtube.com/@omzen_space
  line: https://lin.ee/Yo6cnTl
  cv: false

exclude:
  - demo/
  - cvless.gemspec
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
